// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;


/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {




   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 
    public static final class ArmConstants {
        public static final double kP = 0.1;
        public static final double kI = 0;
        public static final double kD = 0;
        public static final double kF = 0;
        public static final int kEncoderChannelA = 4;
        public static final int kEncoderChannelB = 5;
        public static final int kArmTalonID = 3;
        public static final double kPIDTolerance = 2;
        public static final double kMaxHeight = -98;
        public static final double k2cube = -80;
        public static final double k1cube = -75;
        public static final double kMinHeight = -3;
    }
    public static final class OIConstants{
        public static final int kDriver1ControllerID = 0;
        public static final int kDriver2ControllerID = 1;
    }

    public static final class ClawConstants{
        public static final double kClawOpenMax = 0.97;
        public static final double kClawCloseMin = 0.53;
    }

    public static final class MarkerConstants{
        public static final double kMarkerVertical = 0;
        public static final double kMarkerHorizontal = 90;
    }


}