// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
 import com.ctre.phoenix.motorcontrol.FeedbackDevice;
 import com.ctre.phoenix.motorcontrol.NeutralMode;
 import com.ctre.phoenix.motorcontrol.StatusFrameEnhanced;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class SUBDrivetrain extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_TalonSRX leftDriveMotor;
private WPI_TalonSRX rightDriveMotor;
private DifferentialDrive differentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public SUBDrivetrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
leftDriveMotor = new WPI_TalonSRX(1);
 
    /* Factory default hardware to prevent unexpected behavior */
leftDriveMotor.configFactoryDefault();

        /* Invert Motor? and set Break Mode */
leftDriveMotor.setInverted(true);
leftDriveMotor.setNeutralMode(NeutralMode.Coast);

        /* Set the peak and nominal outputs */
leftDriveMotor.configNominalOutputForward(0, 30);
leftDriveMotor.configNominalOutputReverse(0, 30);
leftDriveMotor.configPeakOutputForward(1, 30);
leftDriveMotor.configPeakOutputReverse(-1, 30);
        











        

rightDriveMotor = new WPI_TalonSRX(2);
 
    /* Factory default hardware to prevent unexpected behavior */
rightDriveMotor.configFactoryDefault();

        /* Invert Motor? and set Break Mode */
rightDriveMotor.setInverted(false);
rightDriveMotor.setNeutralMode(NeutralMode.Coast);

        /* Set the peak and nominal outputs */
rightDriveMotor.configNominalOutputForward(0, 30);
rightDriveMotor.configNominalOutputReverse(0, 30);
rightDriveMotor.configPeakOutputForward(1, 30);
rightDriveMotor.configPeakOutputReverse(-1, 30);
        











        

differentialDrive = new DifferentialDrive(leftDriveMotor, rightDriveMotor);
 addChild("differentialDrive",differentialDrive);
 differentialDrive.setSafetyEnabled(true);
differentialDrive.setExpiration(0.1);
differentialDrive.setMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
    
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void Drive(double speed, double rotation) {
        differentialDrive.curvatureDrive(speed, rotation, true);
    }

}

